# Generated by Django 4.0.4 on 2022-04-11 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mirai', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
